# Generated by Django 4.2.7 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Amazone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category_image", models.ImageField(upload_to="upload/category/")),
                (
                    "Category_name",
                    models.CharField(default="", max_length=100, null=True),
                ),
            ],
        ),
    ]
